wallpapers:
  general: $HOME/.wallpapers/Arknights
  slideshow_delay: 600
  lockscreen: $HOME/.wallpapers/Arknights
  lockscreen_slideshow_delay: 60
  lockscreen_converted: $HOME/.lockscreen
system:
  dim_screen_delay: 300
  lock_session_delay: 360
  sleep_delay: 300
